# Generated by Django 5.2.5 on 2025-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionistprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Front office', 'Front office'), ('Billing', 'Billing'), ('OPD', 'OPD'), ('Emergency', 'Emergency')], max_length=100),
        ),
    ]
