# Generated by Django 5.2.5 on 2025-11-20 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_patient_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('dispatched', 'Dispatched'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_ambulance_trips', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
        ),
    ]
