# Generated by Django 5.2.5 on 2025-11-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
        ('patient', '0002_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='current_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver_phone',
            field=models.CharField(default=77777, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='vehicle_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('OnTrip', 'On Trip'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='AmbulanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField(default='Hospital Base')),
                ('trip_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulance.ambulance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_calls', to='patient.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='AmbulanceTrip',
        ),
    ]
