# Generated by Django 5.2.5 on 2025-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_remove_ambulance_contact_remove_ambulance_vehicle_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver_phone',
            field=models.CharField(default='+91 ', max_length=15),
        ),
    ]
